-- Queries:

-- 1. Find the item that has the minimum weight.
SELECT ITEMNO, DESCRIPTION, WEIGHT
FROM ITEMS
WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

-- 2. Find the different warehouses in "Pune".
SELECT DISTINCT WNAME
FROM WAREHOUSES
WHERE CITY = 'Pune';

-- 3. Find the details of items ordered by a customer named "Mr. Patil".
SELECT CNAME, DESCRIPTION, ORDERED_QUANTITY
FROM CUSTOMER C
JOIN ORDERS O ON C.CNO = O.CUSTOMER_ID
JOIN ITEM_ORDERS IO ON O.ONO = IO.ORDER_ID
JOIN ITEMS I ON IO.ITEM_ID = I.ITEMNO
WHERE CNAME = 'Mr. Patil';

-- 4. Find a Warehouse that has the maximum number of stores.
SELECT WNAME, COUNT(SID) AS StoreCount
FROM WAREHOUSES W
JOIN STORES S ON W.WID = S.WAREHOUSE_ID
GROUP BY WNAME
ORDER BY StoreCount DESC
LIMIT 1;

-- 5. Find an item that is ordered for a minimum number of times.
SELECT ITEMNO, DESCRIPTION, COUNT(ORDER_ID) AS OrderCount
FROM ITEMS I
LEFT JOIN ITEM_ORDERS IO ON I.ITEMNO = IO.ITEM_ID
GROUP BY ITEMNO, DESCRIPTION
ORDER BY OrderCount ASC
LIMIT 1;

-- 6. Find the detailed orders given by each customer.
SELECT CNAME, ONO, ODATE, DESCRIPTION, ORDERED_QUANTITY
FROM CUSTOMER C
JOIN ORDERS O ON C.CNO = O.CUSTOMER_ID
JOIN ITEM_ORDERS IO ON O.ONO = IO.ORDER_ID
JOIN ITEMS I ON IO.ITEM_ID = I.ITEMNO;
